## Baylands Park, Sunnyvale — real terrain under a real orthophoto.
##
## Data: drone/sim/godot/assets/baylands/, generated by
## drone/sim/tools/fetch_baylands.py from USGS 3DEP elevation (public domain),
## USDA NAIP orthophotography (public domain) and OpenStreetMap (ODbL). Local
## ENU frame, metres, origin at the region's south-west corner, so the whole
## 3095 x 3334 m region is positive east/north.
##
## HOW THIS DIFFERS FROM manhattan, which is the other real-world env:
##
##   * manhattan is boxes on a flat plane. Here the ground is a heightfield —
##     0 to 33 m of levees, sloughs and the rise toward the Caribbean Dr
##     business park. Terrain is the only thing out here a low aircraft can
##     fly into, so it has to be collidable, not just drawn.
##   * The look comes from a photograph, not from geometry. At altitude a
##     0.86 m/px orthophoto on real terrain reads as the actual place. That
##     trade is right for a marsh and would be wrong for a city: there is
##     almost nothing here with a facade.
##
## Buildings still use manhattan's representation exactly — axis-aligned rects
## plus a height — so they drop into the same occupancy grid and the same
## analytic slab test for occlusion, with no new machinery. There are 181 of
## them (the business park's edge), against manhattan's 45k, so a single
## MultiMesh is more than enough.
##
## HEIGHT CAVEAT, worth knowing before trusting a near-miss: only 21 of the 181
## buildings carry any height in OSM. The rest are inferred by footprint size
## (see fetch_baylands.py) and each records its source in `hs`. The fallback
## deliberately leans TALL, because a box that is too short lets an aircraft
## through a building that is really there, while one that is too tall only
## costs some airspace.
extends Node3D

const SceneKit = preload("res://scripts/scene_kit.gd")
const DATA_PATH := "res://assets/baylands/baylands.json"
const TERRAIN_PATH := "res://assets/baylands/terrain.png"
const ORTHO_PATH := "res://assets/baylands/ortho.jpg"
const FacadeKit = preload("res://scripts/facade_kit.gd")
const LightingKit = preload("res://scripts/lighting_kit.gd")

## Occupancy-grid cell size. The region is ~3.1 km across; at manhattan's 5 m
## that is a 619 x 667 grid, which is comfortable, and 5 m still resolves a
## levee top (~6-10 m wide) as one to two cells.
const OCC_RES := 5.0

## Render resolution of the terrain mesh. The heightmap is 1024^2, but a mesh
## at that density is ~2M triangles for ground that is nearly flat over most of
## its area. 256 gives ~12 m posts, which holds the levee shapes that matter
## visually; ground_height() still samples the FULL 1024 heightmap, so
## collision is not degraded by this choice.
const MESH_RES := 256

## Terrain counts as an obstacle to the router wherever it stands higher than
## this above the local datum. The marsh floor is 0-2 m and the levees 3-5 m,
## so this keeps the flat ground flyable while marking the built-up rise.
const TERRAIN_OCC_M := 8.0

var WALLS: Array = []
var doors: Dictionary = {}
var DOOR_PANELS: Dictionary = {}
var props: Array = []

# Buildings, parallel arrays exactly as env_manhattan holds them.
var _rects: Array[Rect2] = []
var _heights: PackedFloat32Array = PackedFloat32Array()

# Terrain: row-major heights in metres, _tw x _th samples spanning the region.
var _terrain: PackedFloat32Array = PackedFloat32Array()
var _tw := 0
var _th := 0
var _east := 0.0
var _north := 0.0
var _hmin := 0.0
var _hmax := 0.0

var _grid_w := 0
var _grid_h := 0

# Trees: parallel arrays. Position is ENU, r is crown radius, h is TOTAL
# height (trunk + crown). See fetch_baylands.py — positions come from the
# imagery, heights are inferred from crown radius and are not measured.
var _tree_pos: PackedVector2Array = PackedVector2Array()
var _tree_r: PackedFloat32Array = PackedFloat32Array()
var _tree_h: PackedFloat32Array = PackedFloat32Array()
# Coarse lookup so collision does not scan 11k trees per query.
var _tree_bins: Dictionary = {}
const TREE_BIN := 25.0


func _ready() -> void:
	SceneKit.build(self, false, 0)     # sky + light; ground comes from the ortho
	# SceneKit's shadow reach and fog are tuned for a few hundred metres; this
	# region is 3.3 km. Per-env so the shared setup (and the gates measured
	# against it) is untouched.
	LightingKit.for_large_env(self, 3500.0)
	_drop_scenekit_ground()
	_load_dataset()
	_build_terrain()
	_render_buildings()
	_render_trees()
	_grid_w = int(ceil(_east / OCC_RES))
	_grid_h = int(ceil(_north / OCC_RES))


func grid_config() -> Dictionary:
	return {"res": OCC_RES, "origin": [0.0, 0.0], "w": _grid_w, "h": _grid_h}


## SceneKit lays down a fixed 2000 m green plane centred on the origin. The
## region is 3.1 km and starts at the origin rather than straddling it, so that
## plane would both z-fight the terrain and stick out past it as a green apron.
## Same reasoning as env_manhattan's sky-dome removal.
## Matched by TYPE, not by name: SceneKit adds its floor without naming it, so
## it arrives as an auto-named "MeshInstance3D" and any name-based lookup
## silently misses it. That failure is not subtle on screen but it is subtle in
## code — the marsh floor is 0-2 m and SceneKit's plane sits at y=0, so the two
## z-fight across the whole region and the green wins almost everywhere.
##
## The StaticBody3D floor collider is deliberately LEFT in place: it is what
## landed props rest on, and at y=0 it sits at or below the terrain everywhere
## here (the heightmap's minimum is 0).
func _drop_scenekit_ground() -> void:
	var dome := get_node_or_null("sky_dome")
	if dome:
		dome.queue_free()
	for child in get_children():
		if child is MeshInstance3D and child.mesh is PlaneMesh:
			child.queue_free()


# ------------------------------------------------------------------------ data

func _load_dataset() -> void:
	var f := FileAccess.open(DATA_PATH, FileAccess.READ)
	if f == null:
		push_error("[env_baylands] missing %s — run drone/sim/tools/fetch_baylands.py" % DATA_PATH)
		return
	var doc: Dictionary = JSON.parse_string(f.get_as_text())
	f.close()

	var b: Array = doc.get("bounds_enu", [0, 0, 3095, 3334])
	_east = float(b[2])
	_north = float(b[3])

	var t: Dictionary = doc.get("terrain", {})
	_hmin = float(t.get("min_m", 0.0))
	_hmax = float(t.get("max_m", 0.0))
	_load_heightmap()

	for item in doc.get("buildings", []):
		var r: Array = item["r"]
		var rect := Rect2(float(r[0]), float(r[1]), float(r[2]), float(r[3]))
		_rects.append(rect)
		_heights.append(float(item["h"]))
		WALLS.append(rect)

	for tree in doc.get("trees", []):
		var tp: Array = tree["p"]
		_tree_pos.append(Vector2(float(tp[0]), float(tp[1])))
		_tree_r.append(float(tree["r"]))
		_tree_h.append(float(tree["h"]))
	_bin_trees()

	print("[env_baylands] %d buildings, %d trees, terrain %.1f-%.1f m over %.0f x %.0f m"
		% [_rects.size(), _tree_pos.size(), _hmin, _hmax, _east, _north])


## Decode the 16-bit heightmap. The PNG stores (h - min) / (max - min); the
## fetcher already flipped it so row 0 is SOUTH, matching +north = +row here.
func _load_heightmap() -> void:
	var img := Image.load_from_file(TERRAIN_PATH)
	if img == null:
		push_error("[env_baylands] missing %s" % TERRAIN_PATH)
		return
	_tw = img.get_width()
	_th = img.get_height()
	_terrain.resize(_tw * _th)
	var span := _hmax - _hmin
	for y in _th:
		var row := y * _tw
		for x in _tw:
			# 16-bit greyscale arrives in the red channel as 0..1.
			_terrain[row + x] = _hmin + img.get_pixel(x, y).r * span


## Terrain height in metres at an ENU position, bilinearly interpolated.
##
## This is the collision surface. It samples the full-resolution heightmap, not
## the coarser render mesh, so what an aircraft hits is the real 1 m LIDAR
## ground rather than whatever the triangles happened to do.
func ground_height(east: float, north: float) -> float:
	if _tw == 0:
		return 0.0
	var fx: float = clampf(east / _east, 0.0, 1.0) * float(_tw - 1)
	var fy: float = clampf(north / _north, 0.0, 1.0) * float(_th - 1)
	var x0 := int(fx)
	var y0 := int(fy)
	var x1: int = mini(x0 + 1, _tw - 1)
	var y1: int = mini(y0 + 1, _th - 1)
	var tx := fx - float(x0)
	var ty := fy - float(y0)
	var h00 := _terrain[y0 * _tw + x0]
	var h10 := _terrain[y0 * _tw + x1]
	var h01 := _terrain[y1 * _tw + x0]
	var h11 := _terrain[y1 * _tw + x1]
	return lerpf(lerpf(h00, h10, tx), lerpf(h01, h11, tx), ty)


## Cells the router must treat as blocked because the GROUND is high there.
## fixedwing_manager builds its occupancy from WALLS; terrain is reported
## separately so envs without relief are unaffected.
func terrain_occupancy(res: float) -> PackedVector2Array:
	var out := PackedVector2Array()
	var nx := int(ceil(_east / res))
	var ny := int(ceil(_north / res))
	for gy in ny:
		for gx in nx:
			if ground_height((gx + 0.5) * res, (gy + 0.5) * res) >= TERRAIN_OCC_M:
				out.append(Vector2(gx, gy))
	return out


# --------------------------------------------------------------------- render

func _build_terrain() -> void:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var step_e := _east / float(MESH_RES)
	var step_n := _north / float(MESH_RES)
	for gy in MESH_RES:
		for gx in MESH_RES:
			var e0 := gx * step_e
			var e1 := e0 + step_e
			var n0 := gy * step_n
			var n1 := n0 + step_n
			# Godot is y-up with -z = north, so ENU (e, n) maps to (e, h, -n).
			_quad(st, e0, e1, n0, n1)
	st.generate_normals()

	var mi := MeshInstance3D.new()
	mi.name = "terrain"
	mi.mesh = st.commit()
	var img := Image.load_from_file(ORTHO_PATH)
	# Mipmaps are not optional here. This is a 3600 px texture stretched over
	# 3.1 km and almost always viewed at a grazing angle, which is the worst
	# case for a non-mipmapped sampler: without them the ground shimmers into
	# blurred mush at any distance. Anisotropic filtering is what keeps it
	# legible when the view is nearly along the surface, which for an aircraft
	# camera is most of the time.
	img.generate_mipmaps()
	var mat := StandardMaterial3D.new()
	mat.albedo_texture = ImageTexture.create_from_image(img)
	mat.texture_filter = BaseMaterial3D.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS_ANISOTROPIC
	# LIT, not unshaded — with a darkened albedo to compensate.
	#
	# Unshaded was the first fix here, to stop the scene sun double-lighting a
	# photograph that already contains one. It worked and cost more than it
	# bought: an unshaded material does not RECEIVE shadows, so the city cast
	# nothing onto its own ground, which is most of what makes an aerial shot
	# read as real. Scaling albedo down instead lands at about the same
	# brightness under sun+ambient while keeping the surface in the shadow
	# pass.
	mat.albedo_color = Color(0.55, 0.55, 0.55)
	mat.roughness = 1.0
	mat.metallic = 0.0
	mi.material_override = mat
	add_child(mi)


func _quad(st: SurfaceTool, e0: float, e1: float, n0: float, n1: float) -> void:
	var p00 := Vector3(e0, ground_height(e0, n0), -n0)
	var p10 := Vector3(e1, ground_height(e1, n0), -n0)
	var p01 := Vector3(e0, ground_height(e0, n1), -n1)
	var p11 := Vector3(e1, ground_height(e1, n1), -n1)
	# UVs are the ENU position over the region, so the orthophoto lands exactly
	# where it was photographed. V is flipped because image row 0 is north.
	var uv00 := Vector2(e0 / _east, 1.0 - n0 / _north)
	var uv10 := Vector2(e1 / _east, 1.0 - n0 / _north)
	var uv01 := Vector2(e0 / _east, 1.0 - n1 / _north)
	var uv11 := Vector2(e1 / _east, 1.0 - n1 / _north)
	st.set_uv(uv00); st.add_vertex(p00)
	st.set_uv(uv01); st.add_vertex(p01)
	st.set_uv(uv11); st.add_vertex(p11)
	st.set_uv(uv00); st.add_vertex(p00)
	st.set_uv(uv11); st.add_vertex(p11)
	st.set_uv(uv10); st.add_vertex(p10)


## Buildings as one instanced box mesh, sitting ON the terrain rather than on
## y=0 — the business park is 3-4 m above the marsh, and a box at zero would
## float or sink by that much.
func _render_buildings() -> void:
	if _rects.is_empty():
		return
	var mm := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	var box := BoxMesh.new()
	box.size = Vector3.ONE
	mm.mesh = box
	mm.instance_count = _rects.size()
	for i in _rects.size():
		var r: Rect2 = _rects[i]
		var h: float = _heights[i]
		var cx := r.position.x + r.size.x * 0.5
		var cn := r.position.y + r.size.y * 0.5
		var base := ground_height(cx, cn)
		var t := Transform3D(Basis().scaled(Vector3(r.size.x, h, r.size.y)),
							 Vector3(cx, base + h * 0.5, -cn))
		mm.set_instance_transform(i, t)

	var mmi := MultiMeshInstance3D.new()
	mmi.name = "buildings"
	mmi.multimesh = mm
	mmi.material_override = _building_material()
	add_child(mmi)


## Roofs from the orthophoto, walls from the CC0 facade photographs.
##
## Two different sources on one building, deliberately. The roof comes from the
## site's own orthophoto sampled at the building's real ENU position, so from
## above a box is indistinguishable from the photo it sits in — it IS that
## roof, not a texture that resembles one. The walls cannot come from there: an
## orthophoto is shot straight down and holds no side-on information at all, so
## they use the same shared photographic facade set as manhattan_photo.
##
## Getting this wrong in the obvious direction (flat colour boxes over the
## photo) made the business park read as a field of paper cut-outs.
func _building_material() -> ShaderMaterial:
	var code := """
shader_type spatial;
render_mode cull_back;

uniform sampler2D ortho : source_color, filter_linear_mipmap_anisotropic;
uniform sampler2DArray facades : source_color, filter_linear_mipmap_anisotropic;
uniform float spans[8];
uniform float layers = 7.0;
uniform vec2 region;
uniform vec3 wall_fallback : source_color = vec3(0.60, 0.59, 0.56);
uniform float has_facades = 0.0;

varying vec3 v_world;
varying vec3 v_nrm;
varying vec3 v_metres;
varying float v_layer;
varying float v_span;

float hash1(float n) { return fract(sin(n) * 43758.5453123); }

void vertex() {
    vec3 sc = vec3(length(MODEL_MATRIX[0].xyz),
                   length(MODEL_MATRIX[1].xyz),
                   length(MODEL_MATRIX[2].xyz));
    v_metres = VERTEX * sc;
    v_world = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
    v_nrm = normalize((MODEL_MATRIX * vec4(NORMAL, 0.0)).xyz);
    float seed = hash1(dot(MODEL_MATRIX[3].xyz, vec3(0.031, 0.017, 0.043)));
    v_layer = floor(seed * layers);
    v_span = spans[int(v_layer)];
}

void fragment() {
    if (v_nrm.y > 0.5) {
        // Same mapping the terrain uses, so the roof lines up with the ground
        // texture around it to the pixel. -z is north, hence the flip.
        vec2 uv = vec2(v_world.x / region.x, 1.0 - (-v_world.z) / region.y);
        ALBEDO = texture(ortho, uv).rgb;
        ROUGHNESS = 1.0;
    } else if (has_facades > 0.5) {
        float across = abs(v_nrm.x) > 0.5 ? v_metres.z : v_metres.x;
        vec2 uv = vec2(across, v_metres.y) / v_span;
        vec3 c = texture(facades, vec3(uv, v_layer)).rgb;
        ALBEDO = c;
        float gloss = 1.0 - clamp(dot(c, vec3(0.33)), 0.0, 1.0);
        ROUGHNESS = mix(0.85, 0.3, gloss);
        METALLIC = gloss * 0.25;
    } else {
        // No facade set fetched: faint storey banding, which is still the only
        // height cue a monocular camera gets out here.
        float band = 0.90 + 0.10 * step(0.5, fract(v_metres.y / 3.6));
        ALBEDO = wall_fallback * band;
        ROUGHNESS = 0.9;
    }
}
"""
	var sh := Shader.new()
	sh.code = code
	var mat := ShaderMaterial.new()
	mat.shader = sh
	var img := Image.load_from_file(ORTHO_PATH)
	img.generate_mipmaps()
	mat.set_shader_parameter("ortho", ImageTexture.create_from_image(img))
	mat.set_shader_parameter("region", Vector2(_east, _north))

	var kit := FacadeKit.load_set()
	if kit.is_empty():
		push_warning("[env_baylands] no facade set — run drone/sim/tools/fetch_facades.py")
	else:
		mat.set_shader_parameter("facades", kit["array"])
		mat.set_shader_parameter("spans", kit["spans"])
		mat.set_shader_parameter("layers", float(kit["count"]))
		mat.set_shader_parameter("has_facades", 1.0)
		print("[env_baylands] %d CC0 facades on walls, ortho roofs" % kit["count"])
	return mat


# ------------------------------------------------------------------ occlusion

## Distance to the first structure OR terrain along a ray, or max_dist.
##
## Buildings use env_manhattan's exact slab test. Terrain is marched instead of
## solved: a heightfield has no closed form, and at 181 buildings there is
## ample budget for a 5 m step. The step is the accuracy — good enough to know
## a levee is between the camera and a target, which is what this answers.
func raycast_structures(from: Vector3, dir: Vector3, max_dist: float) -> float:
	var best := max_dist
	for i in _rects.size():
		var base := ground_height(_rects[i].position.x + _rects[i].size.x * 0.5,
								  _rects[i].position.y + _rects[i].size.y * 0.5)
		var d := _ray_box(from, dir, _rects[i], base + _heights[i], best)
		if d >= 0.0 and d < best:
			best = d
	var step := 5.0
	var t := step
	while t < best:
		var p := from + dir * t
		if p.y <= ground_height(p.x, -p.z):
			return t
		t += step
	return best


## Slab test against an axis-aligned prism standing on the ground, in ENU.
func _ray_box(from: Vector3, dir: Vector3, r: Rect2, top: float, max_dist: float) -> float:
	var lo := 0.0
	var hi := max_dist
	# x (east)
	var bounds := [[r.position.x, r.position.x + r.size.x, from.x, dir.x],
				   [0.0, top, from.y, dir.y],
				   [-(r.position.y + r.size.y), -r.position.y, from.z, dir.z]]
	for b in bounds:
		var b0: float = b[0]
		var b1: float = b[1]
		var o: float = b[2]
		var d: float = b[3]
		if absf(d) < 1e-6:
			if o < b0 or o > b1:
				return -1.0
			continue
		var t0 := (b0 - o) / d
		var t1 := (b1 - o) / d
		if t0 > t1:
			var tmp := t0
			t0 = t1
			t1 = tmp
		lo = maxf(lo, t0)
		hi = minf(hi, t1)
		if lo > hi:
			return -1.0
	return lo


func env_state() -> Dictionary:
	return {
		"env": "baylands",
		"region_m": [_east, _north],
		"terrain_m": [_hmin, _hmax],
		"buildings": _rects.size(),
	}


func add_wall(rect: Rect2, height: float = 12.0) -> void:
	_rects.append(rect)
	_heights.append(height)
	WALLS.append(rect)

func _bin_trees() -> void:
	for i in _tree_pos.size():
		var p := _tree_pos[i]
		var key := Vector2i(int(p.x / TREE_BIN), int(p.y / TREE_BIN))
		if not _tree_bins.has(key):
			_tree_bins[key] = PackedInt32Array()
		var arr: PackedInt32Array = _tree_bins[key]
		arr.append(i)
		_tree_bins[key] = arr


## Height of the highest thing at this position — terrain, or a tree crown
## standing on it. This is what an aircraft actually collides with, and it is
## deliberately SEPARATE from ground_height(): that one has to stay pure
## terrain because the terrain mesh and the buildings are placed with it, and
## folding canopy into it would stand buildings on top of trees.
func collision_height(east: float, north: float) -> float:
	var h := ground_height(east, north)
	var gx := int(east / TREE_BIN)
	var gy := int(north / TREE_BIN)
	for dx in [-1, 0, 1]:
		for dy in [-1, 0, 1]:
			var key := Vector2i(gx + dx, gy + dy)
			if not _tree_bins.has(key):
				continue
			for i in (_tree_bins[key] as PackedInt32Array):
				var p := _tree_pos[i]
				if Vector2(east, north).distance_to(p) <= _tree_r[i]:
					h = maxf(h, ground_height(p.x, p.y) + _tree_h[i])
	return h


## Trees as two MultiMesh draws, trunks and crowns.
##
## The crowns sample the orthophoto from above, exactly as the building roofs
## do. The photo ALREADY contains every one of these trees seen from directly
## overhead — that is where their positions came from — so a crown tinted from
## the photo at its own position sits invisibly on top of the tree it was
## derived from, and only reveals itself as the view goes oblique.
func _render_trees() -> void:
	if _tree_pos.is_empty():
		return
	var crown_mesh := SphereMesh.new()
	crown_mesh.radius = 1.0
	crown_mesh.height = 2.0
	crown_mesh.radial_segments = 6
	crown_mesh.rings = 4

	var trunk_mesh := CylinderMesh.new()
	trunk_mesh.top_radius = 0.18
	trunk_mesh.bottom_radius = 0.26
	trunk_mesh.height = 1.0
	trunk_mesh.radial_segments = 5

	var crowns := MultiMesh.new()
	crowns.transform_format = MultiMesh.TRANSFORM_3D
	crowns.mesh = crown_mesh
	crowns.instance_count = _tree_pos.size()
	var trunks := MultiMesh.new()
	trunks.transform_format = MultiMesh.TRANSFORM_3D
	trunks.mesh = trunk_mesh
	trunks.instance_count = _tree_pos.size()

	for i in _tree_pos.size():
		var p := _tree_pos[i]
		var base := ground_height(p.x, p.y)
		var r: float = _tree_r[i]
		var h: float = _tree_h[i]
		var crown_c := base + h - r
		crowns.set_instance_transform(i, Transform3D(
			Basis().scaled(Vector3(r, r * 0.85, r)), Vector3(p.x, crown_c, -p.y)))
		var tl := maxf(crown_c - r * 0.6 - base, 0.5)
		trunks.set_instance_transform(i, Transform3D(
			Basis().scaled(Vector3(1.0, tl, 1.0)), Vector3(p.x, base + tl * 0.5, -p.y)))

	var cm := MultiMeshInstance3D.new()
	cm.name = "tree_crowns"
	cm.multimesh = crowns
	cm.material_override = _crown_material()
	add_child(cm)

	var tm := MultiMeshInstance3D.new()
	tm.name = "tree_trunks"
	tm.multimesh = trunks
	var tmat := StandardMaterial3D.new()
	tmat.albedo_color = Color(0.24, 0.19, 0.14)
	tmat.roughness = 1.0
	tm.material_override = tmat
	add_child(tm)


func _crown_material() -> ShaderMaterial:
	var code := """
shader_type spatial;
render_mode cull_back;

uniform sampler2D ortho : source_color, filter_linear_mipmap_anisotropic;
uniform vec2 region;

varying vec3 v_world;
varying vec3 v_nrm;

void vertex() {
    v_world = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
    v_nrm = normalize((MODEL_MATRIX * vec4(NORMAL, 0.0)).xyz);
}

void fragment() {
    // Tint from the photo at this crown's own ENU position, so the tree
    // matches the one painted underneath it.
    vec2 uv = vec2(v_world.x / region.x, 1.0 - (-v_world.z) / region.y);
    vec3 c = texture(ortho, uv).rgb;
    // Three corrections, all needed. The sampled pixel is a sunlit crown seen
    // from directly above, so used as-is on a whole sphere it is far too
    // bright and too grey — the first attempt rendered as pale bubbles.
    //   1. push strongly toward green, since the photo pixel is desaturated
    //      by the atmosphere it was shot through,
    //   2. scale down hard: this is a lit material, so sun plus ambient adds
    //      most of the brightness back,
    //   3. darken the underside, which never sees the sun at all.
    c = mix(c, c * vec3(0.38, 0.92, 0.32), 0.85);
    c *= 0.62;
    float under = clamp(-v_nrm.y, 0.0, 1.0);
    ALBEDO = c * mix(1.0, 0.35, under);
    ROUGHNESS = 1.0;
    SPECULAR = 0.05;
}
"""
	var sh := Shader.new()
	sh.code = code
	var mat := ShaderMaterial.new()
	mat.shader = sh
	var img := Image.load_from_file(ORTHO_PATH)
	img.generate_mipmaps()
	mat.set_shader_parameter("ortho", ImageTexture.create_from_image(img))
	mat.set_shader_parameter("region", Vector2(_east, _north))
	return mat

