## Manhattan — the real city, built from NYC Open Data building footprints.
##
## Data: drone/sim/godot/assets/manhattan/buildings.json, generated by
## drone/sim/tools/fetch_manhattan.py from NYC Open Data dataset 5zhs-2jue
## (public domain). ~103k buildings with real footprints and real roof heights,
## in a local ENU frame (metres east/north) with its origin at Battery Park.
## Heights are METRES here; the source publishes feet and the tool converts.
##
## Every building is an axis-aligned rectangular prism sitting on flat ground —
## footprint rect plus height. That is the whole geometry, and it is why this
## env needs no physics bodies at all:
##
##   * Routing sees buildings through the occupancy grid, which is built from
##     the same footprint rects (WALLS).
##   * Occlusion is a ray-vs-prism slab test (see raycast_structures), answered
##     analytically against a uniform-grid index. Exact for boxes, and it costs
##     nothing to have 103k of them.
##
## A StaticBody3D per building would be ~103k physics nodes for queries a slab
## test answers exactly. Rendering is one MultiMesh draw, so the whole city is
## one instanced mesh plus a flat array of AABBs.
extends Node3D

const SceneKit = preload("res://scripts/scene_kit.gd")
const DATA_PATH := "res://assets/manhattan/buildings.json"

## Cell size for the building index. Manhattan's avenues are ~280 m apart and
## its streets ~80 m, so 100 m tiles put a handful of buildings in each cell
## while keeping the DDA walk short.
const TILE := 100.0

## Occupancy-grid cell size for this env. The open-field scenes use 1 m over a
## few hundred metres; at that resolution the island would be ~190 million
## cells, and `observed` is allocated per aircraft. 5 m still leaves an ~18 m
## street 3-4 cells wide, which is what routing actually needs.
const OCC_RES := 5.0

# Clip window in ENU metres (east0, north0, east1, north1), or empty for the
# whole island. Set via --env-region on the command line.
var _clip: Array = []

## Vertical exaggeration, `--building-scale`. Real Manhattan is mostly low-rise
## — median building 12 m, 99th percentile 91 m — so from a 100 m cruise the
## city reads as a flat carpet even though the towers are correct (verified:
## Empire State renders 378 m against a real 381 m roof). Scaling up trades
## fidelity for a more legible skyline; 1.0 is the real city.
var _height_scale := 1.0

var WALLS: Array = []
var doors: Dictionary = {}
var DOOR_PANELS: Dictionary = {}
var props: Array = []

# Buildings as flat parallel data: rect (Rect2, ENU) + height (m).
var _rects: Array[Rect2] = []
var _heights: PackedFloat32Array = PackedFloat32Array()
# Uniform-grid index: tile key -> PackedInt32Array of building indices, plus the
# tallest building in each tile so a ray flying above a whole tile skips it.
var _index: Dictionary = {}
var _tile_max_h: Dictionary = {}

var _origin := Vector2.ZERO      # ENU of grid cell (0,0)
var _offset := Vector2.ZERO      # slice centre subtracted to re-centre on origin
var _grid_w := 0
var _grid_h := 0
var _sim_t := 0.0
var _tallest := 0.0


func _ready() -> void:
	SceneKit.build(self, false, 0)   # sky/ground/light only — no tree scatter
	_drop_sky_dome()
	_height_scale = maxf(0.1, float(IpcServer._get_launch_arg("--building-scale", "1.0")))
	_clip = _parse_region()
	_load_city()
	_build_index()
	_add_city_ground()
	_render_city()
	_place_vehicles()
	FixedWingManager.register_env(self)
	print("[env_manhattan] ready — %d buildings, tallest %.0f m (scale %.1fx), grid %dx%d @ %.0f m" %
		[_rects.size(), _tallest, _height_scale, _grid_w, _grid_h, OCC_RES])


## Grid geometry for FixedWingManager. Sized to whatever slice of the city was
## actually loaded, because a structure outside the grid is invisible to the
## envelope guard and the leg-crossing check — those fail open, not closed.
func grid_config() -> Dictionary:
	return {"res": OCC_RES, "origin": [_origin.x, _origin.y],
			"w": _grid_w, "h": _grid_h}


func _parse_region() -> Array:
	var arg := IpcServer._get_launch_arg("--env-region", "")
	if arg == "":
		return []
	var parts := arg.split(",")
	if parts.size() != 4:
		push_warning("[env_manhattan] --env-region needs east0,north0,east1,north1")
		return []
	return [float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3])]


# ------------------------------------------------------------------------ data
func _load_city() -> void:
	if not ResourceLoader.exists(DATA_PATH) and not FileAccess.file_exists(DATA_PATH):
		push_warning("[env_manhattan] missing " + DATA_PATH +
			" — run drone/sim/tools/fetch_manhattan.py")
		_origin = Vector2(-50.0, -150.0)
		_grid_w = 600
		_grid_h = 300
		return
	var f := FileAccess.open(DATA_PATH, FileAccess.READ)
	var doc = JSON.parse_string(f.get_as_text())
	f.close()
	if doc == null or not doc.has("buildings"):
		push_warning("[env_manhattan] could not parse " + DATA_PATH)
		return

	var min_x := INF
	var min_y := INF
	var max_x := -INF
	var max_y := -INF
	for b in doc["buildings"]:
		var r: Array = b["r"]
		var rect := Rect2(float(r[0]), float(r[1]), float(r[2]), float(r[3]))
		if not _clip.is_empty():
			if rect.position.x + rect.size.x < _clip[0] or rect.position.x > _clip[2]:
				continue
			if rect.position.y + rect.size.y < _clip[1] or rect.position.y > _clip[3]:
				continue
		var h := float(b["h"]) * _height_scale
		_rects.append(rect)
		_heights.append(h)
		_tallest = maxf(_tallest, h)
		WALLS.append(rect)
		min_x = minf(min_x, rect.position.x)
		min_y = minf(min_y, rect.position.y)
		max_x = maxf(max_x, rect.position.x + rect.size.x)
		max_y = maxf(max_y, rect.position.y + rect.size.y)

	if _rects.is_empty():
		push_warning("[env_manhattan] clip window selected no buildings")
		_origin = Vector2(-50.0, -150.0)
		_grid_w = 600
		_grid_h = 300
		return

	# Re-centre the loaded slice on the world origin.
	#
	# Midtown sits ~6 km north of the Battery Park datum, and SceneKit's ground
	# plane is 2000 m centred on the origin — so an un-recentred slice renders as
	# a city floating over empty space, miles from where anyone looking at the
	# Godot viewport (or the default camera) is pointed. It also wastes
	# occupancy-grid span on the empty gap back to the datum.
	#
	# The shift is recorded and reported in env_state as `datum_offset_enu`, so
	# a sim coordinate can still be turned back into a real one: add the offset,
	# then undo the 29 deg street-grid rotation.
	_offset = Vector2((min_x + max_x) * 0.5, (min_y + max_y) * 0.5)
	for i in _rects.size():
		_rects[i].position -= _offset
	WALLS.clear()
	for r in _rects:
		WALLS.append(r)
	min_x -= _offset.x
	max_x -= _offset.x
	min_y -= _offset.y
	max_y -= _offset.y

	# One tile of margin so an aircraft just outside the built area is still
	# inside the grid rather than silently unguarded.
	_origin = Vector2(floor(min_x / OCC_RES) * OCC_RES - OCC_RES,
					  floor(min_y / OCC_RES) * OCC_RES - OCC_RES)
	_grid_w = int(ceil((max_x - _origin.x) / OCC_RES)) + 1
	_grid_h = int(ceil((max_y - _origin.y) / OCC_RES)) + 1


func _build_index() -> void:
	for i in _rects.size():
		var r := _rects[i]
		var h := _heights[i]
		var tx0 := int(floor(r.position.x / TILE))
		var ty0 := int(floor(r.position.y / TILE))
		var tx1 := int(floor((r.position.x + r.size.x) / TILE))
		var ty1 := int(floor((r.position.y + r.size.y) / TILE))
		for tx in range(tx0, tx1 + 1):
			for ty in range(ty0, ty1 + 1):
				var key := Vector2i(tx, ty)
				if not _index.has(key):
					_index[key] = PackedInt32Array()
					_tile_max_h[key] = 0.0
				_index[key].append(i)
				_tile_max_h[key] = maxf(_tile_max_h[key], h)


## Drop SceneKit's finite sky dome.
##
## It is a flipped sphere of radius 3000 m, which works when the whole scene fits
## inside it. Manhattan is 21 km long, so the aircraft flies outside its own
## skydome and sees it edge-on as a huge dark disc sitting on the horizon. The
## WorldEnvironment that SceneKit also installs draws an infinite procedural sky,
## so removing the mesh loses nothing and cannot clip.
func _drop_sky_dome() -> void:
	var dome := get_node_or_null("sky_dome")
	if dome:
		dome.queue_free()


## NOT PRESENT: atmospheric haze. Recorded because it is worth not retrying.
##
## The city renders as untextured grey boxes, which leaves a monocular camera
## almost no depth cue, and the theory was that this is why the on-Orin VLM could
## not tell "climb over it" from "go around it" — a 90 m building 60 m away and a
## 200 m tower 400 m away project to the same grey shape. Exponential fog was
## added to supply aerial perspective.
##
## It did not work, on either count. Scored against an 18-frame labelled set the
## model went 8/18 to 9/18, against a chance floor of 6/18 — no real change; it
## answers "over" for most frames whatever is in them. And the fog could not be
## tuned to serve this scene: useful ranges here span 50 m to 20 km, and at a
## density that read as haze up close (0.0016) a top-down of the island from
## 4.2 km came back a uniform blue rectangle. Even at 0.00012 the park's green
## measured (106,140,168) from 4 km — indistinguishable from the city beside it —
## while at 250 m it was correctly (36,67,62).
##
## So it was removed rather than left switched off: it cost the wide shots and
## bought nothing. If depth cues are wanted later, texture the facades instead;
## that adds gradient at every range rather than trading near against far.


## Ground sized to the city: water everywhere, land only where the island is.
##
## SceneKit's ground is a fixed 2000 m plane centred on the origin, which is
## smaller than the city for anything beyond a few blocks — and the whole island
## is 11 x 22 km. Standing off to photograph the skyline put the camera past the
## plane's edge, where the frame is just the inside of the sky sphere: "land and
## sky and no buildings". Both planes here are sized to the loaded slice plus a
## margin, and both sit ABOVE SceneKit's plane — underneath it, the field's green
## wins everywhere within its 2000 m and the city sits on grass.
##
## Heights are spaced ~0.5 m apart rather than the few centimetres used before.
## With a 40 km far plane the depth buffer has little precision to spare out at
## the shoreline, and coplanar planes that far out z-fight into a shimmering mess.
const Y_WATER := 0.1
const Y_LAND := 0.6
const Y_PARK := 1.1

## North extent of each land band. The island silhouette is recovered from the
## footprints (see _add_land), so this is the resolution of the coastline: 80 m
## is about one Manhattan block, fine enough that the shore reads as a shore
## rather than as a rectangle, coarse enough to stay a few hundred quads.
const LAND_BAND := 80.0

## Push the shoreline out past the outermost building. Without it the waterfront
## buildings sit with their outer wall exactly on the water's edge, which from
## the air looks like the city is sinking.
const LAND_MARGIN := 70.0


## Central Park, in the dataset's own ENU frame (metres east/north of the
## Battery Park datum, street-grid-rotated), BEFORE the slice re-centring.
##
## Derived from its four street corners — 59th/110th St by 5th/8th Ave — pushed
## through the same projection tools/fetch_manhattan.py uses, so it lands in
## exactly the frame the footprints do. Three checks that it is right:
##   * the four corners come out axis-aligned to within 3 m, which independently
##     confirms the 29 deg street-grid rotation;
##   * the box measures 803 x 4130 m against the real park's 860 x 4110 m;
##   * only 50 of the 11562 buildings in that north band fall inside it (0.4%),
##     i.e. it really is the hole in the building data.
## Kept in dataset coordinates, not sim ones, because `_offset` depends on which
## slice was loaded — same treatment the footprints get.
const PARK_RECT := Rect2(-1049.0, 7998.0, 803.0, 4130.0)


func _add_city_ground() -> void:
	_add_water()
	_add_land()
	_add_park()


## Central Park as a green slab on top of the asphalt.
##
## Sits above the land plane rather than replacing part of it, so the land mesh
## stays one simple slab and there is no hole to keep in sync with it.
func _add_park() -> void:
	var r := Rect2(PARK_RECT.position - _offset, PARK_RECT.size)
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	_land_quad(st, r.position.x, r.position.x + r.size.x,
			   r.position.y, r.position.y + r.size.y, Y_PARK)

	var mi := MeshInstance3D.new()
	mi.name = "central_park"
	mi.mesh = st.commit()
	var mat := StandardMaterial3D.new()
	# Brighter and more saturated than a "correct" park green needs to be. The
	# aerial haze is blue and desaturating, so a dark 0.20/0.42/0.18 came out
	# blue-grey at 2 km and read as water rather than grass. Colour here has to
	# survive the fog, not match a paint chip.
	mat.albedo_color = Color(0.30, 0.60, 0.24)
	mat.roughness = 1.0
	mat.cull_mode = BaseMaterial3D.CULL_DISABLED
	mi.material_override = mat
	add_child(mi)
	print("[env_manhattan] central park: %.0f x %.0f m at east %.0f, north %.0f" %
		[r.size.x, r.size.y, r.position.x, r.position.y])


func _add_water() -> void:
	# Margin sized past the 40 km camera far plane, not merely "generous". At
	# 12 km the plane's own edge was visible from altitude as a straight line
	# with the sky's ground colour beyond it. It is one quad either way, so
	# there is no reason to be thrifty.
	var w := maxf(_grid_w * OCC_RES, 2000.0) + 80000.0
	var h := maxf(_grid_h * OCC_RES, 2000.0) + 80000.0
	var mi := MeshInstance3D.new()
	mi.name = "water"
	var pm := PlaneMesh.new()
	pm.size = Vector2(w, h)
	mi.mesh = pm
	var mat := StandardMaterial3D.new()
	mat.albedo_color = Color(0.05, 0.13, 0.30)   # dark blue
	# Water is the one surface here that should catch the sun, so unlike the
	# asphalt it gets a low roughness and some metallic to give a specular sheen.
	mat.roughness = 0.22
	mat.metallic = 0.45
	mi.material_override = mat
	mi.position = Vector3(_origin.x + _grid_w * OCC_RES * 0.5, Y_WATER,
						  -(_origin.y + _grid_h * OCC_RES * 0.5))
	add_child(mi)


## The island, as one mesh of north-aligned bands.
##
## There is no coastline in the dataset — it is building footprints and nothing
## else. But the footprints only exist on land, so their east extent in each
## band of north IS the island's width there, to within one waterfront block.
## Binning by north and taking min/max east per bin recovers a recognisable
## Manhattan: narrow at the Battery, widest around 14th St, tapering past
## Harlem. Bands with no buildings at all stay water, which is what puts a gap
## in the shoreline instead of bridging across open river.
##
## Cheap, too: it is the same pass the occupancy grid already makes over _rects,
## and the result is a few hundred quads in one draw.
func _add_land() -> void:
	if _rects.is_empty():
		return
	var bands := {}
	for i in _rects.size():
		var r := _rects[i]
		var b0 := int(floor(r.position.y / LAND_BAND))
		var b1 := int(floor((r.position.y + r.size.y) / LAND_BAND))
		for b in range(b0, b1 + 1):
			var e0 := r.position.x
			var e1 := r.position.x + r.size.x
			if bands.has(b):
				var v: Vector2 = bands[b]
				bands[b] = Vector2(minf(v.x, e0), maxf(v.y, e1))
			else:
				bands[b] = Vector2(e0, e1)

	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for b in bands:
		var span: Vector2 = bands[b]
		var e0: float = span.x - LAND_MARGIN
		var e1: float = span.y + LAND_MARGIN
		# Bands are emitted across their FULL north extent, so neighbours share
		# an edge exactly and the seam between them cannot leak water through.
		var n0: float = float(b) * LAND_BAND
		var n1: float = n0 + LAND_BAND
		_land_quad(st, e0, e1, n0, n1)
	# No generate_tangents(): tangents need UVs, the quads carry none, and the
	# material is a flat untextured colour with no normal map to orient.

	var mi := MeshInstance3D.new()
	mi.name = "land"
	mi.mesh = st.commit()
	var mat := StandardMaterial3D.new()
	# Asphalt, not the field's green — but lighter than it first was (0.19), which
	# read as a black void next to the water and made the shoreline look like a
	# hole rather than a bank. Streets from the air are lighter than deep water.
	mat.albedo_color = Color(0.30, 0.30, 0.29)
	mat.roughness = 1.0
	# Winding is not worth getting right for a flat slab seen only from above;
	# normals are set explicitly and culling is off, so neither face can vanish.
	mat.cull_mode = BaseMaterial3D.CULL_DISABLED
	mi.material_override = mat
	add_child(mi)
	print("[env_manhattan] land: %d bands of %.0f m north" % [bands.size(), LAND_BAND])


func _land_quad(st: SurfaceTool, e0: float, e1: float, n0: float, n1: float,
		y: float = Y_LAND) -> void:
	# ENU (east, north) -> Godot local (east, up, -north).
	var a := Vector3(e0, y, -n0)
	var b := Vector3(e1, y, -n0)
	var c := Vector3(e1, y, -n1)
	var d := Vector3(e0, y, -n1)
	for v in [a, b, c, a, c, d]:
		st.set_normal(Vector3.UP)
		st.add_vertex(v)


# --------------------------------------------------------------------- render
## One MultiMesh for the whole city: 103k boxes in a single draw call. Per-tile
## colour variation only — individual buildings don't need unique materials.
func _render_city() -> void:
	var box := BoxMesh.new()
	box.size = Vector3.ONE
	var mat := StandardMaterial3D.new()
	# Concrete grey as the BASE albedo, with the per-instance colour below acting
	# only as a tint on top of it.
	#
	# It used to rely on the instance colour alone, leaving albedo_color at its
	# default white — and the city rendered near-white, while the land plane at
	# albedo 0.19 rendered nearly black in the same frame. Since both are lit
	# identically that is not exposure, it is the instance colours not reaching
	# the shader at all. Whatever the cause, a real base albedo means the
	# buildings are concrete-coloured whether or not the tint applies, instead of
	# depending on it.
	mat.albedo_color = Color(0.52, 0.53, 0.55)
	mat.vertex_color_use_as_albedo = true
	mat.roughness = 0.92
	box.material = mat

	var mm := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	mm.use_colors = true
	mm.mesh = box
	mm.instance_count = _rects.size()

	var rng := RandomNumberGenerator.new()
	rng.seed = 7
	for i in _rects.size():
		var r := _rects[i]
		var h := _heights[i]
		var cx := r.position.x + r.size.x * 0.5
		var cy := r.position.y + r.size.y * 0.5
		var basis := Basis.IDENTITY.scaled(Vector3(r.size.x, h, r.size.y))
		mm.set_instance_transform(i, Transform3D(basis, Vector3(cx, h * 0.5, -cy)))
		# A tint around 1.0, not an absolute colour: this MULTIPLIES the base
		# albedo above, so values near 1 vary the facades without deciding how
		# dark the city is.
		var g := rng.randf_range(0.80, 1.12)
		mm.set_instance_color(i, Color(g, g * rng.randf_range(0.97, 1.03),
									   g * rng.randf_range(1.0, 1.08)))

	var mmi := MultiMeshInstance3D.new()
	mmi.multimesh = mm
	mmi.name = "city"
	add_child(mmi)


# ------------------------------------------------------- analytic ray queries
## Ray vs the city, as a slab test against axis-aligned prisms over the tile
## index. Returns the nearest hit distance along `dir` within `max_dist`, or -1.0.
##
## `from`/`dir` are ENU (x=east, y=north, z=up); dir need not be normalised but
## max_dist is measured in units of |dir|=1, so pass a normalised dir.
func raycast_structures(from: Vector3, dir: Vector3, max_dist: float) -> float:
	var best := -1.0
	# Walk the tiles the ray crosses (2D DDA in the east/north plane) instead of
	# testing every building.
	var t := 0.0
	var step := TILE * 0.5   # half a tile keeps the walk from skipping corners
	var seen := {}
	while t <= max_dist:
		var p := from + dir * t
		var key := Vector2i(int(floor(p.x / TILE)), int(floor(p.y / TILE)))
		t += step
		if seen.has(key):
			continue
		seen[key] = true
		if not _index.has(key):
			continue
		# If the ray is above everything in this tile for its whole crossing,
		# nothing here can occlude — the common case for a drone over a city of
		# mostly low buildings.
		if p.z > float(_tile_max_h[key]) and dir.z >= 0.0:
			continue
		for i in _index[key]:
			var d := _ray_box(from, dir, _rects[i], _heights[i], max_dist)
			if d >= 0.0 and (best < 0.0 or d < best):
				best = d
	return best


## Slab test against one prism: footprint rect extruded from z=0 to z=height.
func _ray_box(from: Vector3, dir: Vector3, r: Rect2, h: float, max_dist: float) -> float:
	var lo := 0.0
	var hi := max_dist
	# East, north, up — the prism's three slab pairs.
	var mins := PackedFloat64Array([r.position.x, r.position.y, 0.0])
	var maxs := PackedFloat64Array([r.position.x + r.size.x, r.position.y + r.size.y, h])
	var o := PackedFloat64Array([from.x, from.y, from.z])
	var d := PackedFloat64Array([dir.x, dir.y, dir.z])
	for a in 3:
		if absf(d[a]) < 1e-9:
			if o[a] < mins[a] or o[a] > maxs[a]:
				return -1.0
			continue
		var inv := 1.0 / d[a]
		var t0 := (mins[a] - o[a]) * inv
		var t1 := (maxs[a] - o[a]) * inv
		if t0 > t1:
			var tmp := t0
			t0 = t1
			t1 = tmp
		lo = maxf(lo, t0)
		hi = minf(hi, t1)
		if lo > hi:
			return -1.0
	return lo


# --------------------------------------------------------- structure sensing
## Buildings as "wall" detections, so the perception stack can see the city.
##
## FixedWingManager.detect() only walks `_env.props`, and this env deliberately
## has no per-building nodes — the city is one MultiMesh over a flat array of
## rects. That makes every building invisible to detect(), and detect() is the
## only obstacle channel the VLM gets (situation.ObstacleTracker keeps rows whose
## label is "wall"). Without this the model is told midtown is clear sky.
##
## So they are synthesised analytically, from the same tile index the raycasts
## use: nearest-first, FOV-culled, occlusion by the city itself, capped at
## MAX_STRUCTURE_ROWS. Labelled "wall" because that is the label the tracker
## already understands, and carrying `top_z` so the tracker can tell the model
## whether a given building can be overflown — which for a 472 m tower under a
## 120 m envelope ceiling is the difference between a detour and a crash.
##
## Only buildings that actually reach the aircraft's altitude are reported. A
## 20 m brownstone is not an obstacle to something cruising at 70 m, and filling
## the block with hundreds of them would bury the towers that matter.
const MAX_STRUCTURE_ROWS := 6
const STRUCTURE_REPORT_MARGIN := 5.0   # m below us a roof must reach to count


func structure_detections(pos_enu: Vector3, sensor_yaw: float, cfg: Dictionary) -> Array:
	var max_range: float = float(cfg.get("range", 400.0))
	var hfov_half: float = float(cfg.get("hfov_half", 0.6))
	var vfov_half: float = float(cfg.get("vfov_half", 0.6))
	var look_down: float = float(cfg.get("look_down", 0.0))
	var here := Vector2(pos_enu.x, pos_enu.y)
	var forward := Vector2(cos(sensor_yaw), sin(sensor_yaw))
	var floor_z: float = pos_enu.z - STRUCTURE_REPORT_MARGIN

	# Gather candidates from the tiles the sensor cone can reach.
	var hits: Array = []
	var seen := {}
	var t0 := Vector2i(int(floor((here.x - max_range) / TILE)),
					   int(floor((here.y - max_range) / TILE)))
	var t1 := Vector2i(int(floor((here.x + max_range) / TILE)),
					   int(floor((here.y + max_range) / TILE)))
	for tx in range(t0.x, t1.x + 1):
		for ty in range(t0.y, t1.y + 1):
			var key := Vector2i(tx, ty)
			if not _index.has(key):
				continue
			# Whole-tile reject: if nothing here reaches us, skip the tile.
			if float(_tile_max_h[key]) <= floor_z:
				continue
			for i in _index[key]:
				if seen.has(i):
					continue
				seen[i] = true
				var h: float = _heights[i]
				if h <= floor_z:
					continue
				var r: Rect2 = _rects[i]
				# Nearest point of the footprint, not its centre: for a block
				# 200 m long the centre can be far outside the cone while the
				# near corner is dead ahead, and reporting the centre would
				# place the obstacle well off to one side of where it is.
				var near_pt := Vector2(
					clampf(here.x, r.position.x, r.position.x + r.size.x),
					clampf(here.y, r.position.y, r.position.y + r.size.y))
				var rel := near_pt - here
				var dist := rel.length()
				if dist > max_range or dist < 0.5:
					continue
				var bearing := forward.angle_to(rel.normalized())
				if absf(bearing) > hfov_half:
					continue
				# A building is a TALL object, so test its whole vertical span
				# against the FOV, not just its roof.
				#
				# The props pass gets away with testing a single point because a
				# truck is small. Testing only the roof here rejected every tower
				# worth knowing about: the sensor is pitched 15 deg down with a
				# 35 deg half-FOV, so it sees from 50 deg below the horizon to
				# just 20 deg above it, and the roof of a 120 m tower seen from
				# 70 m at 100 m range sits at 26.6 deg — out of frame, while its
				# facade fills the middle of the picture. Detections came back
				# empty in a canyon surrounded by towers.
				var vert_top := atan2(h - pos_enu.z, dist) + look_down
				var vert_bot := atan2(-pos_enu.z, dist) + look_down
				if vert_top < -vfov_half or vert_bot > vfov_half:
					continue
				# Report the highest part actually in frame: for a tower that
				# overtops the view this pins ny at the top edge, which is the
				# honest reading — "it extends past the top of the image".
				var vert := clampf(vert_top, -vfov_half, vfov_half)
				hits.append({"i": i, "d": dist, "p": near_pt, "h": h,
							 "bearing": bearing, "vert": vert})

	hits.sort_custom(func(a, b): return a["d"] < b["d"])

	var out: Array = []
	for hit in hits:
		if out.size() >= MAX_STRUCTURE_ROWS:
			break
		var p: Vector2 = hit["p"]
		var h: float = hit["h"]
		# Occlusion by other buildings, using the env's own slab test. Aimed at
		# the roof edge rather than the wall's foot, since that is the part the
		# aircraft has to clear and the part a camera would actually see.
		var target := Vector3(p.x, p.y, minf(h, pos_enu.z + 20.0))
		var dir := target - pos_enu
		var span := dir.length()
		if span > 1.0:
			var d := raycast_structures(pos_enu, dir / span, span - 2.0)
			if d >= 0.0 and d < span - 2.0:
				continue
		var nx: float = clampf(0.5 + (float(hit["bearing"]) / hfov_half) * 0.5, 0.0, 1.0)
		var ny: float = clampf(0.5 - (float(hit["vert"]) / vfov_half) * 0.5, 0.0, 1.0)
		var range_penalty: float = clampf((float(hit["d"]) - 40.0) / 40.0, 0.0, 1.0) * 0.3
		out.append({
			"label": "wall",
			"confidence": clampf(0.9 - range_penalty, 0.2, 0.9),
			"nx": nx,
			"ny": ny,
			"world": [p.x, p.y, h],
			"top_z": h,
		})
	return out


# ------------------------------------------------------------------- vehicles
## A findable target and a decoy, placed on open ground (not inside a building)
## near the centre of whatever slice was loaded.
func _place_vehicles() -> void:
	var c := _open_spot()
	props.append(_make_vehicle("target", "pickup truck", c,
		Vector3(5.4, 1.5, 2.2), Color(0.75, 0.13, 0.12), true))
	props.append(_make_vehicle("decoy", "car", c + Vector2(60.0, -40.0),
		Vector3(4.3, 1.3, 1.9), Color(0.15, 0.24, 0.62), false))


func _open_spot() -> Vector2:
	var c := _origin + Vector2(_grid_w * OCC_RES * 0.5, _grid_h * OCC_RES * 0.5)
	# Spiral out until a point is clear of every footprint — dropping a truck
	# inside a tower would make it permanently unreachable.
	for ring in range(0, 60):
		for ang in range(0, 12):
			var p := c + Vector2(cos(ang * PI / 6.0), sin(ang * PI / 6.0)) * (ring * 12.0)
			var clear := true
			var key := Vector2i(int(floor(p.x / TILE)), int(floor(p.y / TILE)))
			if _index.has(key):
				for i in _index[key]:
					if _rects[i].grow(4.0).has_point(p):
						clear = false
						break
			if clear:
				return p
	return c


func _make_vehicle(node_name: String, detect_label: String, pos: Vector2,
		size: Vector3, color: Color, is_truck: bool) -> StaticBody3D:
	var body := StaticBody3D.new()
	body.name = "veh_" + node_name
	body.set_meta("label", detect_label)
	body.set_meta("is_anomaly", false)
	body.set_meta("top_z", size.y + (0.9 if is_truck else 0.0))
	var col := CollisionShape3D.new()
	var cshape := BoxShape3D.new()
	cshape.size = size
	col.shape = cshape
	body.add_child(col)
	body.add_child(_box_mesh(size, Vector3.ZERO, color))
	if is_truck:
		var top := size.y * 0.5
		var cab := Vector3(size.x * 0.34, 1.2, size.z * 0.94)
		body.add_child(_box_mesh(cab, Vector3(size.x * 0.28, top + cab.y * 0.5, 0.0),
			color.darkened(0.1)))
	body.position = Vector3(pos.x, size.y * 0.5, -pos.y)
	body.collision_layer = 2   # LAYER_PROPS
	body.collision_mask = 0
	add_child(body)
	return body


func _box_mesh(size: Vector3, local_pos: Vector3, color: Color) -> MeshInstance3D:
	var mesh := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = size
	mesh.mesh = bm
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	mat.roughness = 0.7
	mat.metallic = 0.2
	mesh.material_override = mat
	mesh.position = local_pos
	return mesh


# -------------------------------------------------------------- env contract
func env_state() -> Dictionary:
	var t: Vector2 = Vector2.ZERO
	var d: Vector2 = Vector2.ZERO
	if props.size() >= 2:
		t = Vector2(props[0].position.x, -props[0].position.z)
		d = Vector2(props[1].position.x, -props[1].position.z)
	return {
		"env": "manhattan",
		"target_kind": "pickup truck",
		"target_enu": [t.x, t.y],
		"decoy_car_enu": [d.x, d.y],
		"sim_t": _sim_t,
		"buildings": _rects.size(),
		"tallest": _tallest,
		"bounds_enu": [_origin.x, _origin.y,
					   _origin.x + _grid_w * OCC_RES, _origin.y + _grid_h * OCC_RES],
		"occ_res": OCC_RES,
		"height_scale": _height_scale,
		"datum_offset_enu": [_offset.x, _offset.y],
		"grid_rotation_deg": 29.0,
		"home_a": [t.x - 220.0, t.y + 20.0],
		"home_b": [t.x - 220.0, t.y - 20.0],
		"spawn_alt": 60.0,
	}


func add_wall(rect: Rect2, height: float = 60.0) -> void:
	WALLS.append(rect)
	_rects.append(rect)
	_heights.append(height)
	_tallest = maxf(_tallest, height)
	_build_index()


func _process(delta: float) -> void:
	_sim_t += delta
