//! Manhattan — the real city, built from NYC Open Data building footprints.
//!
//! Direct port of `drone/sim/godot/scripts/env_manhattan.gd`. Data is
//! `drone/sim/godot/assets/manhattan/buildings.json`, generated by
//! `drone/sim/tools/fetch_manhattan.py` from NYC Open Data dataset 5zhs-2jue
//! (public domain): ~45k buildings with real footprints and real roof heights,
//! in a local ENU frame (metres east/north) with its origin at Battery Park.
//! Heights are METRES here; the source publishes feet and the tool converts.
//!
//! Every building is an axis-aligned rectangular prism sitting on flat ground —
//! footprint rect plus height. That is the whole geometry, and it is why this
//! env needs no physics bodies at all:
//!
//!   * routing sees buildings through the occupancy grid, built from the same
//!     footprint rects;
//!   * occlusion is a ray-vs-prism slab test answered analytically against a
//!     uniform-grid index. Exact for boxes, and it costs nothing to have 45k.
//!
//! The asset path is shared with the Godot project rather than copied: the two
//! backends must fly the identical city or a parity check means nothing.

use crate::geom::{ray_box, Rect2};
use crate::scenario::{DetectionRow, Environment, GridConfig, Prop, Scenario, SensorCfg};
use bevy::math::{IVec2, Vec2, Vec3};
use bevy::platform::collections::HashMap;

/// Cell size for the building index. Manhattan's avenues are ~280 m apart and
/// its streets ~80 m, so 100 m tiles put a handful of buildings in each cell
/// while keeping the DDA walk short.
const TILE: f32 = 100.0;

/// Occupancy-grid cell size for this env. The open-field scenes use 1 m over a
/// few hundred metres; at that resolution the island would be ~190 million
/// cells, and `observed` is allocated per aircraft. 5 m still leaves an ~18 m
/// street 3-4 cells wide, which is what routing actually needs.
pub const OCC_RES: f32 = 5.0;

/// Heights of the three ground slabs, spaced ~0.5 m apart rather than the few
/// centimetres a small scene can get away with: with a 40 km far plane the
/// depth buffer has little precision to spare out at the shoreline, and
/// coplanar planes that far out z-fight into a shimmering mess.
pub const Y_WATER: f32 = 0.1;
pub const Y_LAND: f32 = 0.6;
pub const Y_PARK: f32 = 1.1;

/// North extent of each land band, i.e. the resolution of the recovered
/// coastline. 80 m is about one Manhattan block.
const LAND_BAND: f32 = 80.0;

/// Push the shoreline out past the outermost building, or the waterfront
/// buildings sit with their outer wall exactly on the water's edge and from
/// the air the city looks like it is sinking.
const LAND_MARGIN: f32 = 70.0;

/// Central Park, in the dataset's own ENU frame (metres east/north of the
/// Battery Park datum, street-grid-rotated), BEFORE the slice re-centring.
/// Kept in dataset coordinates because `offset` depends on which slice was
/// loaded — the same treatment the footprints get.
const PARK_RECT: Rect2 = Rect2 {
    pos: Vec2::new(-1049.0, 7998.0),
    size: Vec2::new(803.0, 4130.0),
};

/// Only buildings that actually reach the aircraft's altitude are reported. A
/// 20 m brownstone is not an obstacle to something cruising at 70 m, and
/// filling the block with hundreds of them would bury the towers that matter.
const MAX_STRUCTURE_ROWS: usize = 6;
const STRUCTURE_REPORT_MARGIN: f32 = 5.0;

pub struct Manhattan {
    /// Buildings as flat parallel data: footprint rect (ENU) + height (m).
    rects: Vec<Rect2>,
    heights: Vec<f32>,
    /// Uniform-grid index: tile key -> building indices, plus the tallest
    /// building in each tile so a ray flying above a whole tile skips it.
    index: HashMap<IVec2, Vec<u32>>,
    tile_max_h: HashMap<IVec2, f32>,

    origin: Vec2,
    /// Slice centre subtracted to re-centre the loaded slice on the origin.
    offset: Vec2,
    grid_w: usize,
    grid_h: usize,
    tallest: f32,
    height_scale: f32,
    sim_t: f32,
    props: Vec<Prop>,
    /// Land bands recovered from the footprints, for the ground mesh.
    pub land_bands: Vec<(f32, f32, f32)>,
}

/// Where `buildings.json` lives.
///
/// Shared with the Godot project by default, on purpose: the two backends must
/// fly the identical city or a parity check between them means nothing. When
/// the crate is deployed on its own (rsynced to a GPU host without the rest of
/// the repo) a sibling `assets/` copy is used instead, and
/// `PRESIDIO_MANHATTAN_JSON` overrides both.
fn data_path() -> std::path::PathBuf {
    if let Ok(p) = std::env::var("PRESIDIO_MANHATTAN_JSON") {
        return std::path::PathBuf::from(p);
    }
    let here = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let candidates = [
        // …/drone/sim/bevy -> …/drone/sim/godot/assets/manhattan/…
        here.parent()
            .map(|sim| sim.join("godot/assets/manhattan/buildings.json")),
        // Standalone deployment.
        Some(here.join("assets/manhattan/buildings.json")),
    ];
    for c in candidates.into_iter().flatten() {
        if c.exists() {
            return c;
        }
    }
    here.join("assets/manhattan/buildings.json")
}

impl Manhattan {
    pub fn load(scenario: &Scenario) -> Self {
        let mut m = Manhattan {
            rects: Vec::new(),
            heights: Vec::new(),
            index: HashMap::default(),
            tile_max_h: HashMap::default(),
            origin: Vec2::ZERO,
            offset: Vec2::ZERO,
            grid_w: 0,
            grid_h: 0,
            tallest: 0.0,
            height_scale: scenario.building_scale.max(0.1),
            sim_t: 0.0,
            props: Vec::new(),
            land_bands: Vec::new(),
        };
        m.load_city(scenario.region);
        m.build_index();
        m.build_land_bands();
        m.place_vehicles();
        m
    }

    fn load_city(&mut self, clip: Option<[f32; 4]>) {
        let path = data_path();
        let text = match std::fs::read_to_string(&path) {
            Ok(t) => t,
            Err(e) => {
                eprintln!(
                    "[env_manhattan] missing {} ({e}) — run drone/sim/tools/fetch_manhattan.py",
                    path.display()
                );
                self.fallback_grid();
                return;
            }
        };
        let doc: serde_json::Value = match serde_json::from_str(&text) {
            Ok(d) => d,
            Err(e) => {
                eprintln!("[env_manhattan] could not parse {}: {e}", path.display());
                self.fallback_grid();
                return;
            }
        };
        let Some(buildings) = doc.get("buildings").and_then(|b| b.as_array()) else {
            eprintln!("[env_manhattan] could not parse {}", path.display());
            self.fallback_grid();
            return;
        };

        // The extents are accumulated in f64, with each footprint term widened
        // SEPARATELY before being added, because that is what GDScript's
        // `maxf(max_x, rect.position.x + rect.size.x)` does: reading a
        // `Vector2` component into a GDScript float expression promotes the
        // stored f32 to double, so the edge sum is exact.
        //
        // Adding the two f32s in f32 first and widening the result is a
        // DIFFERENT number, and it is not a rounding curiosity that cancels
        // out: max_x feeds the recentring offset, which is subtracted from
        // every footprint in the slice. For this dataset the widest building's
        // f32 edge sum rounds up 9.7e-05 m, moving the offset 4.6e-05 m, which
        // slid the whole city that far east of where Godot puts it and flipped
        // 649 of the 4,652,648 occupancy cells whose footprint edge lands on a
        // 5 m cell boundary — 584 phantom obstacles and 65 real ones missed.
        let (mut min_x, mut min_y) = (f64::INFINITY, f64::INFINITY);
        let (mut max_x, mut max_y) = (f64::NEG_INFINITY, f64::NEG_INFINITY);

        for b in buildings {
            let Some(r) = b.get("r").and_then(|r| r.as_array()) else {
                continue;
            };
            if r.len() < 4 {
                continue;
            }
            let f = |i: usize| r[i].as_f64().unwrap_or(0.0) as f32;
            let rect = Rect2::new(f(0), f(1), f(2), f(3));
            if let Some(c) = clip {
                if rect.pos.x + rect.size.x < c[0] || rect.pos.x > c[2] {
                    continue;
                }
                if rect.pos.y + rect.size.y < c[1] || rect.pos.y > c[3] {
                    continue;
                }
            }
            let h = b.get("h").and_then(|h| h.as_f64()).unwrap_or(0.0) as f32 * self.height_scale;
            self.rects.push(rect);
            self.heights.push(h);
            self.tallest = self.tallest.max(h);
            min_x = min_x.min(rect.pos.x as f64);
            min_y = min_y.min(rect.pos.y as f64);
            max_x = max_x.max(rect.pos.x as f64 + rect.size.x as f64);
            max_y = max_y.max(rect.pos.y as f64 + rect.size.y as f64);
        }

        if self.rects.is_empty() {
            eprintln!("[env_manhattan] clip window selected no buildings");
            self.fallback_grid();
            return;
        }

        // Re-centre the loaded slice on the world origin.
        //
        // Midtown sits ~6 km north of the Battery Park datum, so an
        // un-recentred slice renders as a city floating over empty space, miles
        // from where any default camera is pointed, and wastes occupancy-grid
        // span on the empty gap back to the datum. The shift is recorded and
        // reported in env_state as `datum_offset_enu`, so a sim coordinate can
        // still be turned back into a real one: add the offset, then undo the
        // 29 deg street-grid rotation.
        self.offset = Vec2::new(
            ((min_x + max_x) * 0.5) as f32,
            ((min_y + max_y) * 0.5) as f32,
        );
        for r in &mut self.rects {
            r.pos -= self.offset;
        }
        min_x -= self.offset.x as f64;
        max_x -= self.offset.x as f64;
        min_y -= self.offset.y as f64;
        max_y -= self.offset.y as f64;

        // One tile of margin so an aircraft just outside the built area is
        // still inside the grid rather than silently unguarded.
        let res = OCC_RES as f64;
        self.origin = Vec2::new(
            ((min_x / res).floor() * res - res) as f32,
            ((min_y / res).floor() * res - res) as f32,
        );
        self.grid_w = ((max_x - self.origin.x as f64) / res).ceil() as usize + 1;
        self.grid_h = ((max_y - self.origin.y as f64) / res).ceil() as usize + 1;
    }

    fn fallback_grid(&mut self) {
        self.origin = Vec2::new(-50.0, -150.0);
        self.grid_w = 600;
        self.grid_h = 300;
    }

    fn build_index(&mut self) {
        self.index.clear();
        self.tile_max_h.clear();
        for i in 0..self.rects.len() {
            let r = self.rects[i];
            let h = self.heights[i];
            let tx0 = (r.pos.x / TILE).floor() as i32;
            let ty0 = (r.pos.y / TILE).floor() as i32;
            let tx1 = ((r.pos.x + r.size.x) / TILE).floor() as i32;
            let ty1 = ((r.pos.y + r.size.y) / TILE).floor() as i32;
            for tx in tx0..=tx1 {
                for ty in ty0..=ty1 {
                    let key = IVec2::new(tx, ty);
                    self.index.entry(key).or_default().push(i as u32);
                    let e = self.tile_max_h.entry(key).or_insert(0.0);
                    *e = e.max(h);
                }
            }
        }
    }

    /// The island, as north-aligned bands.
    ///
    /// There is no coastline in the dataset — it is building footprints and
    /// nothing else. But the footprints only exist on land, so their east
    /// extent in each band of north IS the island's width there, to within one
    /// waterfront block. Binning by north and taking min/max east per bin
    /// recovers a recognisable Manhattan: narrow at the Battery, widest around
    /// 14th St, tapering past Harlem. Bands with no buildings at all stay
    /// water, which is what puts a gap in the shoreline instead of bridging
    /// across open river.
    fn build_land_bands(&mut self) {
        let mut bands: HashMap<i32, Vec2> = HashMap::default();
        for i in 0..self.rects.len() {
            let r = self.rects[i];
            let b0 = (r.pos.y / LAND_BAND).floor() as i32;
            let b1 = ((r.pos.y + r.size.y) / LAND_BAND).floor() as i32;
            for b in b0..=b1 {
                let e0 = r.pos.x;
                let e1 = r.pos.x + r.size.x;
                bands
                    .entry(b)
                    .and_modify(|v| *v = Vec2::new(v.x.min(e0), v.y.max(e1)))
                    .or_insert(Vec2::new(e0, e1));
            }
        }
        let mut keys: Vec<i32> = bands.keys().copied().collect();
        keys.sort_unstable();
        self.land_bands = keys
            .into_iter()
            .map(|b| {
                let span = bands[&b];
                (
                    span.x - LAND_MARGIN,
                    span.y + LAND_MARGIN,
                    b as f32 * LAND_BAND,
                )
            })
            .collect();
    }

    /// A findable target and a decoy, on open ground near the centre of
    /// whatever slice was loaded.
    fn place_vehicles(&mut self) {
        let c = self.open_spot();
        self.props.push(Prop {
            name: "target".into(),
            label: "pickup truck".into(),
            is_anomaly: false,
            top_z: Some(1.5 + 0.9),
            pos: Vec3::new(c.x, c.y, 1.5 * 0.5),
            size: Vec3::new(5.4, 1.5, 2.2),
            color: [0.75, 0.13, 0.12],
            cab: Some((
                Vec3::new(5.4 * 0.34, 1.2, 2.2 * 0.94),
                Vec3::new(5.4 * 0.28, 1.5 * 0.5 + 0.6, 0.0),
            )),
        });
        let d = c + Vec2::new(60.0, -40.0);
        self.props.push(Prop {
            name: "decoy".into(),
            label: "car".into(),
            is_anomaly: false,
            top_z: Some(1.3),
            pos: Vec3::new(d.x, d.y, 1.3 * 0.5),
            size: Vec3::new(4.3, 1.3, 1.9),
            color: [0.15, 0.24, 0.62],
            cab: None,
        });
    }

    /// Spiral out from the slice centre until a point is clear of every
    /// footprint — dropping a truck inside a tower would make it permanently
    /// unreachable.
    fn open_spot(&self) -> Vec2 {
        let c = self.origin
            + Vec2::new(
                self.grid_w as f32 * OCC_RES * 0.5,
                self.grid_h as f32 * OCC_RES * 0.5,
            );
        for ring in 0..60 {
            for ang in 0..12 {
                // f64, deliberately. GDScript evaluates every scalar float
                // expression in double and only narrows when it writes into a
                // Vector2, and here that difference is not cosmetic: at ang=6
                // the angle is exactly PI, where f64 sin is +1.2e-16 and f32
                // sin is -8.7e-8. The sign flip moves the point across the
                // y=0 tile boundary, so the two engines probed DIFFERENT tiles
                // for "is this spot clear" and placed the target 6 m apart —
                // which then moved home_a/home_b and the whole run-in geometry.
                let a = ang as f64 * std::f64::consts::PI / 6.0;
                let off = Vec2::new(a.cos() as f32, a.sin() as f32);
                let p = c + off * (ring as f32 * 12.0);
                let key = IVec2::new((p.x / TILE).floor() as i32, (p.y / TILE).floor() as i32);
                let mut clear = true;
                if let Some(ids) = self.index.get(&key) {
                    for &i in ids {
                        if self.rects[i as usize].grow(4.0).has_point(p) {
                            clear = false;
                            break;
                        }
                    }
                }
                if clear {
                    return p;
                }
            }
        }
        c
    }

    pub fn building_count(&self) -> usize {
        self.rects.len()
    }
    pub fn tallest(&self) -> f32 {
        self.tallest
    }
    pub fn rects(&self) -> &[Rect2] {
        &self.rects
    }
    pub fn heights(&self) -> &[f32] {
        &self.heights
    }
    pub fn origin(&self) -> Vec2 {
        self.origin
    }
    pub fn grid_dims(&self) -> (usize, usize) {
        (self.grid_w, self.grid_h)
    }
    /// Central Park in the loaded slice's own frame.
    pub fn park_rect(&self) -> Rect2 {
        Rect2 {
            pos: PARK_RECT.pos - self.offset,
            size: PARK_RECT.size,
        }
    }
    /// Extent of the water plane. Sized past the 40 km camera far plane, not
    /// merely generously: at 12 km the plane's own edge was visible from
    /// altitude as a straight line with the sky's colour beyond it, and it is
    /// one quad either way.
    pub fn water_extent(&self) -> (Vec2, Vec2) {
        let w = (self.grid_w as f32 * OCC_RES).max(2000.0) + 80_000.0;
        let h = (self.grid_h as f32 * OCC_RES).max(2000.0) + 80_000.0;
        let centre = Vec2::new(
            self.origin.x + self.grid_w as f32 * OCC_RES * 0.5,
            self.origin.y + self.grid_h as f32 * OCC_RES * 0.5,
        );
        (centre, Vec2::new(w, h))
    }
}

impl Environment for Manhattan {
    fn as_any(&self) -> &dyn core::any::Any {
        self
    }

    fn grid_config(&self) -> GridConfig {
        GridConfig {
            res: OCC_RES,
            origin: self.origin,
            w: self.grid_w,
            h: self.grid_h,
        }
    }

    fn walls(&self) -> &[Rect2] {
        &self.rects
    }

    fn wall_heights(&self) -> &[f32] {
        &self.heights
    }

    fn props(&self) -> &[Prop] {
        &self.props
    }

    fn props_mut(&mut self) -> &mut Vec<Prop> {
        &mut self.props
    }

    /// Ray vs the city, as a slab test against axis-aligned prisms over the
    /// tile index. `dir` must be normalised; `max_dist` is in the same units.
    fn raycast_structures(&self, from: Vec3, dir: Vec3, max_dist: f32) -> Option<f32> {
        let mut best: Option<f32> = None;
        // Walk the tiles the ray crosses instead of testing every building.
        // Half a tile per step keeps the walk from skipping corners.
        let step = TILE * 0.5;
        let mut t = 0.0f32;
        let mut seen: HashMap<IVec2, ()> = HashMap::default();
        while t <= max_dist {
            let p = from + dir * t;
            let key = IVec2::new((p.x / TILE).floor() as i32, (p.y / TILE).floor() as i32);
            t += step;
            if seen.insert(key, ()).is_some() {
                continue;
            }
            let Some(ids) = self.index.get(&key) else {
                continue;
            };
            // If the ray is above everything in this tile for its whole
            // crossing, nothing here can occlude — the common case for a drone
            // over a city of mostly low buildings.
            if p.z > *self.tile_max_h.get(&key).unwrap_or(&0.0) && dir.z >= 0.0 {
                continue;
            }
            for &i in ids {
                let i = i as usize;
                if let Some(d) = ray_box(from, dir, &self.rects[i], self.heights[i], max_dist) {
                    if best.is_none_or(|b| d < b) {
                        best = Some(d);
                    }
                }
            }
        }
        best
    }

    /// Buildings as "wall" detections, so the perception stack can see the city.
    ///
    /// The props pass only walks `props`, and this env deliberately has no
    /// per-building object — the city is a flat array of rects. That makes
    /// every building invisible to `detect()`, and `detect()` is the only
    /// obstacle channel the VLM gets (`situation.ObstacleTracker` keeps rows
    /// whose label is "wall"). Without this the model is told midtown is clear
    /// sky. Labelled "wall" because that is the label the tracker already
    /// understands, and carrying `top_z` so it can tell whether a given
    /// building can be overflown — which for a 472 m tower under a 120 m
    /// envelope ceiling is the difference between a detour and a crash.
    fn structure_detections(&self, pos: Vec3, sensor_yaw: f32, cfg: SensorCfg) -> Vec<DetectionRow> {
        let here = Vec2::new(pos.x, pos.y);
        let forward = Vec2::new(sensor_yaw.cos(), sensor_yaw.sin());
        let floor_z = pos.z - STRUCTURE_REPORT_MARGIN;

        struct Hit {
            d: f32,
            p: Vec2,
            h: f32,
            bearing: f32,
            vert: f32,
        }
        let mut hits: Vec<Hit> = Vec::new();
        let mut seen: HashMap<u32, ()> = HashMap::default();

        let t0 = IVec2::new(
            ((here.x - cfg.range) / TILE).floor() as i32,
            ((here.y - cfg.range) / TILE).floor() as i32,
        );
        let t1 = IVec2::new(
            ((here.x + cfg.range) / TILE).floor() as i32,
            ((here.y + cfg.range) / TILE).floor() as i32,
        );
        for tx in t0.x..=t1.x {
            for ty in t0.y..=t1.y {
                let key = IVec2::new(tx, ty);
                let Some(ids) = self.index.get(&key) else {
                    continue;
                };
                // Whole-tile reject: if nothing here reaches us, skip the tile.
                if *self.tile_max_h.get(&key).unwrap_or(&0.0) <= floor_z {
                    continue;
                }
                for &id in ids {
                    if seen.insert(id, ()).is_some() {
                        continue;
                    }
                    let i = id as usize;
                    let h = self.heights[i];
                    if h <= floor_z {
                        continue;
                    }
                    let r = self.rects[i];
                    // Nearest point of the footprint, not its centre: for a
                    // block 200 m long the centre can be far outside the cone
                    // while the near corner is dead ahead, and reporting the
                    // centre would place the obstacle well off to one side of
                    // where it actually is.
                    let near_pt = r.nearest_point(here);
                    let rel = near_pt - here;
                    let dist = rel.length();
                    if dist > cfg.range || dist < 0.5 {
                        continue;
                    }
                    let bearing = crate::enu::angle_to(forward, rel.normalize());
                    if bearing.abs() > cfg.hfov_half {
                        continue;
                    }
                    // A building is a TALL object, so test its whole vertical
                    // span against the FOV, not just its roof. Testing only
                    // the roof rejected every tower worth knowing about: with
                    // the sensor pitched down, the roof of a 120 m tower seen
                    // from 70 m at 100 m range sits above the frame while its
                    // facade fills the middle of the picture.
                    let vert_top = (h - pos.z).atan2(dist) + cfg.look_down;
                    let vert_bot = (-pos.z).atan2(dist) + cfg.look_down;
                    if vert_top < -cfg.vfov_half || vert_bot > cfg.vfov_half {
                        continue;
                    }
                    // Report the highest part actually in frame: for a tower
                    // that overtops the view this pins ny at the top edge,
                    // which is the honest reading.
                    let vert = vert_top.clamp(-cfg.vfov_half, cfg.vfov_half);
                    hits.push(Hit {
                        d: dist,
                        p: near_pt,
                        h,
                        bearing,
                        vert,
                    });
                }
            }
        }

        hits.sort_by(|a, b| a.d.partial_cmp(&b.d).unwrap_or(std::cmp::Ordering::Equal));

        let mut out = Vec::new();
        for hit in hits {
            if out.len() >= MAX_STRUCTURE_ROWS {
                break;
            }
            // Occlusion by other buildings, using this env's own slab test.
            // Aimed at the roof edge rather than the wall's foot, since that is
            // the part the aircraft has to clear and the part a camera sees.
            let target = Vec3::new(hit.p.x, hit.p.y, hit.h.min(pos.z + 20.0));
            let dir = target - pos;
            let span = dir.length();
            if span > 1.0 {
                if let Some(d) = self.raycast_structures(pos, dir / span, span - 2.0) {
                    if d < span - 2.0 {
                        continue;
                    }
                }
            }
            let nx = (0.5 + (hit.bearing / cfg.hfov_half) * 0.5).clamp(0.0, 1.0);
            let ny = (0.5 - (hit.vert / cfg.vfov_half) * 0.5).clamp(0.0, 1.0);
            let range_penalty = ((hit.d - 40.0) / 40.0).clamp(0.0, 1.0) * 0.3;
            out.push(DetectionRow {
                label: "wall".into(),
                confidence: (0.9 - range_penalty).clamp(0.2, 0.9),
                nx,
                ny,
                world: [hit.p.x, hit.p.y, hit.h],
                top_z: Some(hit.h),
                peer_id: None,
                peer_alt: None,
            });
        }
        out
    }

    fn env_state(&self) -> serde_json::Value {
        let t = self
            .props
            .first()
            .map(|p| [p.pos.x, p.pos.y])
            .unwrap_or([0.0, 0.0]);
        let d = self
            .props
            .get(1)
            .map(|p| [p.pos.x, p.pos.y])
            .unwrap_or([0.0, 0.0]);
        serde_json::json!({
            "env": "manhattan",
            "target_kind": "pickup truck",
            "target_enu": t,
            "decoy_car_enu": d,
            "sim_t": self.sim_t,
            "buildings": self.rects.len(),
            "tallest": self.tallest,
            "bounds_enu": [
                self.origin.x,
                self.origin.y,
                self.origin.x + self.grid_w as f32 * OCC_RES,
                self.origin.y + self.grid_h as f32 * OCC_RES
            ],
            "occ_res": OCC_RES,
            "height_scale": self.height_scale,
            "datum_offset_enu": [self.offset.x, self.offset.y],
            "grid_rotation_deg": 29.0,
            "home_a": [t[0] - 220.0, t[1] + 20.0],
            "home_b": [t[0] - 220.0, t[1] - 20.0],
            "spawn_alt": 60.0,
        })
    }

    fn add_wall(&mut self, rect: Rect2, height: f32) {
        self.rects.push(rect);
        self.heights.push(height);
        self.tallest = self.tallest.max(height);
        self.build_index();
    }

    fn advance(&mut self, dt: f32) {
        self.sim_t += dt;
    }
}
